version: '3'
services:
  kafka:
    # ... Kafka configuration ...
    image: wurstmeister/kafka:2.12-2.8.0
    ports:
      - "9092:9092"  # Kafka broker port
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka  # Replace with your Kafka server's hostname
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "my-topic:1:1"  # Define your Kafka topics here
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Link to Zookeeper service

  spark:
    # ... Spark configuration ...
    image: jupyter/all-spark-notebook:spark-3.1.1
    container_name: spark-container
    ports:
      - "4040-4080:4040-4080"
    volumes:
      - ./spark-app:/home/jovyan/work/spark-app
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
  spark-master:
    image: jupyter/all-spark-notebook:spark-3.1.1
    container_name: spark-master-container
    command: ["bin/spark-class", "org.apache.spark.deploy.master.Master"]
    ports:
      - "7077:7077"

  grafana:
    # ... Grafana configuration ...
    image: grafana/grafana:latest
    container_name: grafana-server
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword  # Change this password
    networks:
      - data-pipeline-network


  postgres:
    image: postgres:latest
    container_name: postgres-server
    environment:
      POSTGRES_USER: your_username  # Update with your PostgreSQL username
      POSTGRES_PASSWORD: your_password  # Update with your PostgreSQL password
      POSTGRES_DB: your_database_name  # Update with your PostgreSQL database name
    ports:
      - "5432:5432"
    volumes:
      - ./database/init-scripts:/docker-entrypoint-initdb.d  # Mount SQL scripts for schema creation
    networks:
      - data-pipeline-network

  timescaledb:
    image: timescale/timescaledb:latest-pg13
    container_name: timescaledb-server
    environment:
      POSTGRES_USER: your_username  # Update with your PostgreSQL username
      POSTGRES_PASSWORD: your_password  # Update with your PostgreSQL password
      POSTGRES_DB: your_database_name  # Update with your PostgreSQL database name
    ports:
      - "5433:5432"  # Map a different port to avoid conflicts with PostgreSQL
    volumes:
      - ./database/timescaledb:/docker-entrypoint-initdb.d  # Mount SQL scripts for schema creation
    networks:
      - data-pipeline-network

networks:
  data-pipeline-network:
    driver: bridge
